### ISSUE TITLE
 Thoughts on ISFM outcomes

### ISSUE THREAD

**Issue by Dorcas-Sang** [Dorcas-Sang/ISFM-INTERFACES#5]

**Comment by Dorcas-Sang** [comment]
What I want to do here is to calculate these indicators separately. To have a transparent opinion on the different outcomes separately because I think the benefits do not necessarily have to be about the money. It can be the environmental, nutritional etc,...
The economic outcome is the only one that will boil all the variables down to the monetary benefit.

If the outcomes are separated probably this is how they could look like: 
 1. How much money would a farmer gain with ISFM in a window period of 25 years for example,
 2. How would ISFM increase the soil organic matter in 25 years? Can ISFM fix the soil organic matter of degraded lands?
 3. what about nutrition?
 4..  Would women and men have equal access to resources under ISFM in 25 years? Is going to be balanced? how does ISFM affect social inclusion?
 5. How would crop yield look like (increase, plateau, or decrease) with ISFM in 25 years?

!!!!!!! Gathering thoughts here (Multi-criteria decision approaches maybe?) !!!!!

**Comment by CWWhitney** [comment]
Great that this is moving forward. 

Did you complete the MDCA options as well? 
Maybe these are some separate issues?
