### ISSUE TITLE
Find out how to generate the economomic, environmental, productivity, social and human condition outcomes separately 

### ISSUE THREAD

**Issue by Dorcas-Sang** [Dorcas-Sang/ISFM-INTERFACES#6]

**Comment by CWWhitney** [comment]
@Dorcas-Sang Lots of useful functions in the  decisionSupport collection for this. Feel free to take those and modify them. This process also might benefit from 'if' and 'else' switches. Check my codas_garden model for some recent examples.

**Comment by Dorcas-Sang** [comment]
Done with 4 layers of benefits: 
Farm Profit
Environmental benefits
Household benefits
Total farm-level economic benefits combining the 3 above
